### ISSUE TITLE
can't set localhost on app domain

### ISSUE THREAD

**Issue by tunele** [specious/facebook-cli#1]
I got the following error

App domains must match the domain of the Secure Canvas URL, Mobile Site URL, Unity Binary URL, Site URL or Secure Page Tab URL. Please correct these domains: localhost

**Comment by specious** [comment]
Excellent observation.

I forgot to add in the setup instructions, to first set "Site URL" to "http://localhost".  With that, it works:

![app-settings](https://cloud.githubusercontent.com/assets/451178/18928283/674ec5d4-858d-11e6-8626-6bf06f77dee2.png)

**Comment by tunele** [comment]
Yes thanks, it works fine!

**Comment by specious** [comment]
Hold on, the issue isn't resolved until we fix the setup instructions.  Thanks for confirming!

**Comment by tunele** [comment]
ah ok sorry! Thanks for your job!

All the best,
*A
http://antonellomoro.it

2016-09-28 21:23 GMT+02:00 Ildar Sagdejev notifications@github.com:

**Comment by specious** [comment]
I added detailed [instructions with screenshots](https://github.com/specious/facebook-cli/blob/master/doc/configuration.md).

**Comment by paxperscientiam** [comment]
@specious 

It seems that FB no longer allows the usage of localhost.
https://www.dropbox.com/s/itldmatib2yihya/Screenshot%202017-08-13%2014.33.51.png?dl=0

**Comment by specious** [comment]
@paxperscientiam, I think you diverged slightly from the setup instructions.  Under `App Domains`, enter `localhost`, not `http://localhost`.  Then do `+ Add Platform` and choose `Website`.  Under `Site URL`, type `http://localhost`.

I realize it's a bit confusing, but the instructions are precise because they work.

**Comment by paxperscientiam** [comment]
@specious Ah, you are so right. I totally glossed over the "add platform" bit -- d'oh!

Thanks a lot. `facebook-cli` works great. Being able to submit API commands is awesome!

**Comment by d95mk** [comment]
I've tried putting **localhost** as AppDomain and then http://localhost as Site url under Website. And it does not work. Has something changed since August?

**Comment by specious** [comment]
@d95mk, please come join the discussion at #17.
