### ISSUE TITLE
Not Compatible with Windows 10 

### ISSUE THREAD

**Issue by Redhat007** [specious/facebook-cli#11]
i kept getting a Syntax Error at the following part in the Terminal: facebook-cli config --appid=<app-id> --appsecret=<app-secret>

**Comment by specious** [comment]
Well, those fields shouldn't be blank.  However, I'm curious why you're getting a syntax error.  Could you please post the full output from your terminal?

**Comment by zer0trip** [comment]
Works fine for me on Windows 10.

**Comment by specious** [comment]
Thanks, @SeanCodingOnline.  I suspect it's not a Windows problem, but I'd like to understand the error anyway.

**Comment by specious** [comment]
I'm closing this for now. Please reopen if it's still an issue.
