### ISSUE TITLE
Post to FB page?

### ISSUE THREAD

**Issue by AstroFloyd** [specious/facebook-cli#12]
Thank you for facebook-cli.  I was wondering whether it is possible to post to post a message/image/link/video to an existing (company) page rather than my personal wall.   On the FB apps page, all I can do is create a new page for the app.  (This is a question, not an issue).  Thanks for your time :-)

**Comment by insidenothing** [comment]
just got to this point, then noticed no page command ( yet ) ( learning gem/ruby now )

**Comment by specious** [comment]
I'm excited that you guys are enjoying facebook-cli 👍 

I'm noticing there's a lot of interest in posting to a page or a group.  There are two pull requests open that add group posting ability: #5 and #10.

I'm working on an elegant way to post to your timeline, a page or a group without adding superfluous complexity to the application.

I'm thinking of using Koala's [put_connections](https://github.com/arsduo/koala/blob/a18e1e86f69f99e6b0fb664414f579bb285b055f/lib/koala/api/graph_api_methods.rb#L157) method directly to handle all of that.

**Comment by specious** [comment]
Post to pages and groups using `--to <page-or-group-id-or-alias>`with facebook-cli 1.6.0.

![Example of posting a video to a page using facebook-cli 1.6.0](https://user-images.githubusercontent.com/451178/30509125-9ebde744-9a76-11e7-97a9-474988f04239.png)

![Video posted to a facebook page with facebook-cli](https://user-images.githubusercontent.com/451178/30509127-a6e516fe-9a76-11e7-82f1-2dcbe6c056a8.png)

**Comment by specious** [comment]
I discovered that [put_wall_post()](https://github.com/arsduo/koala/blob/a18e1e86f69f99e6b0fb664414f579bb285b055f/lib/koala/api/graph_api_methods.rb#L288), [put_picture()](https://github.com/arsduo/koala/blob/a18e1e86f69f99e6b0fb664414f579bb285b055f/lib/koala/api/graph_api_methods.rb#L248) and [put_video()](https://github.com/arsduo/koala/blob/a18e1e86f69f99e6b0fb664414f579bb285b055f/lib/koala/api/graph_api_methods.rb#L255) all support a target object (page, group, feed) identifier.

I'm really enjoying @arsduo's wonderful job with Koala.

**Comment by shfrs** [comment]
Hi, I got this error when trying post to group, what's wrong with my command?
`$ facebook-cli post --to 933655546775648 Test`
`$ Koala OAuthException (code 200) HTTP status: 403
  (#200) Insufficient permission to post to target on behalf of the viewer (FB trace id: CSEfqkFSend)`

`$ facebook-cli -v
facebook-cli version 1.6.1`

**Comment by marteaurouge** [comment]
I get the same code 200 error, any help?

**Comment by specious** [comment]
It looks like a permission problem.  @shfrs, are you definitely a member of the [group](https://www.facebook.com/groups/933655546775648) you are trying to post to and are able to post using the standard web interface?

By the way, 1.6.5 is currently the latest version of facebook-cli.  I recommend running:

`gem update facebook-cli`.

**Comment by specious** [comment]
@marteaurouge, could you please post the exact command you are running and the entire output, as well as the version of facebook-cli you've got?

**Comment by paum3** [comment]
Hi I have the same problem.

191684291417171 iD of my private group

$ ./facebook-cli post --to=191684291417171  "hello"
Koala OAuthException (code 200) HTTP status: 403
  (#200) Insufficient permission to post to target on behalf of the viewer (FB trace id: EBcAYwLbICy)

$ ./facebook-cli --version
facebook-cli version 1.6.5
