### ISSUE TITLE
Installing on a remote machine

### ISSUE THREAD

**Issue by insidenothing** [specious/facebook-cli#15]
I was able to copy from a local ubuntu to my headless box. is there a possibility of a copy and paste response for an easier headless install? --headless

**Comment by specious** [comment]
I don't understand what you just said.  Are you talking about the authentication procedure?

**Comment by insidenothing** [comment]
Yes, sorry, i have a linux server in digital ocean, so when the time came to open the browser ( and port for response ) i hit a roadblock. so i set up locally and copied the variable in the settings.

**Comment by specious** [comment]
What if you put the server's IP instead of `localhost` in the app's Site URL field, so the auth token is sent to the right place?

![site-url](https://user-images.githubusercontent.com/451178/30349032-752d9472-97df-11e7-9866-140f061df887.png)

**Comment by insidenothing** [comment]
Yes that worked, Thanks! One note,https://github.com/specious/facebook-cli/blob/master/lib/fbcli/auth.rb has localhost hard coded so i had to replace with my domain before pasting into browser.

**Comment by insidenothing** [comment]
actually, it appears to work but the .facebook-clirc is not updated

**Comment by insidenothing** [comment]
could it be https://github.com/specious/facebook-cli/blob/1b439c3b82fb1b1d687749720481b51af91aba1e/lib/fbcli/auth.rb#L59

**Comment by specious** [comment]
Thanks for pointing this out! 👍 

Very valid use case.  Now I'm wondering if the "Site URL" field in the app setup even plays a role here.

**Comment by specious** [comment]
Some experimentation reveals that yes, the "Site URL" field does need to match the `redirect_uri`.

![facebook-error-siteurl-domain-doesnt-match](https://user-images.githubusercontent.com/451178/30509522-9ba36e1c-9a80-11e7-9ca4-bb6806b4d5f0.png)

**Comment by Enrico204** [comment]
FYI I just tried - and it worked - to use "localhost" with SSH forwarding when installing `facebook-cli` on a remote host: when opening SSH connection you can use `-L3333:127.0.0.1:3333` option to forward TCP port 3333 from local to remote host (actually you can set up forwarding even with ssh already in place).

**Comment by specious** [comment]
Just pushed 1.6.4 (e8f75669ef854cd5f2a30ad72bf9b3fc2acbb0ae), which lets you customize the host name and port for receiving the auth code during login:

`facebook-cli login --host 127.0.0.1 --port 1234`

Thank you guys for the feedback!
