### ISSUE TITLE
Facebook side of new applications creating has changed

### ISSUE THREAD

**Issue by zacekjakub** [specious/facebook-cli#16]
Hey, unfortunately, there is nothing named Website in types of applications when you try to create one on the Facebook side. Could you update the manual please?

Go to the "Settings" tab
Click "Add Platform"
Select "Website"
Set "Site URL" to http://localhost

**Comment by specious** [comment]
If what you're seeing is different from what I'm seeing, could you please post a screenshot?

![facebook-app-select-platform](https://user-images.githubusercontent.com/451178/31040314-ee120f40-a553-11e7-8dc5-54be10729298.png)

**Comment by specious** [comment]
I'm closing this issue for now.  Feedback on and improvements to the setup process would be much appreciated.
