### ISSUE TITLE
Login authentication error: "The domain of this URL isn't included in the app's domains."

### ISSUE THREAD

**Issue by nolangormley** [specious/facebook-cli#17]
I've been having issues logging in with this cli. I have followed the text guide and images and have recreated my development project twice. Every time I run "facebook-cli login" i get the message,

<img width="525" alt="screen shot 2017-10-05 at 12 23 41 pm" src="https://user-images.githubusercontent.com/6481154/31238599-70b2d74a-a9c8-11e7-80d7-2af489c55f4f.png">

and the terminal message,

```
Nolans-MacBook-Pro-2:CS3060_FA2017_A4_GORMLEY nolan$ facebook-cli login
Request permission to use the Facebook API by opening this link in your browser:

https://www.facebook.com/dialog/oauth?client_id=1461925040511825&redirect_uri=http://localhost:3333/&scope=user_likes,user_friends,user_posts,user_photos,user_videos,user_events,publish_actions

Waiting for authorization code on port 3333...

Received unexpected request: error_code=1349048&error_message=Can%27t+Load+URL%3A+The+domain+of+this+URL+isn%27t+included+in+the+app%27s+domains.+To+be+able+to+load+this+URL%2C+add+all+domains+and+subdomains+of+your+app+to+the+App+Domains+field+in+your+app+settings.
Nolans-MacBook-Pro-2:CS3060_FA2017_A4_GORMLEY nolan$ 
```

The only thing that I have noticed is that the API version on the image guide was 2.8 and the current is 2.10.

**Comment by specious** [comment]
Did you add `localhost` to "App Domains" on [this screen](https://github.com/specious/facebook-cli/blob/38541744259bfc393fed6d07a971f61a92c3491d/doc/images/initial-configuration/add-localhost-to-app-domains.png)?

**Comment by nolangormley** [comment]
Yessir.

<img width="1051" alt="screen shot 2017-10-05 at 12 34 34 pm" src="https://user-images.githubusercontent.com/6481154/31238981-9b86502c-a9c9-11e7-88b3-3a30dd8c9c03.png">

also the app is live 

<img width="1048" alt="screen shot 2017-10-05 at 12 35 18 pm" src="https://user-images.githubusercontent.com/6481154/31239072-e9e4ccb2-a9c9-11e7-828d-42730786538a.png">

**Comment by specious** [comment]
Did you click "Save Changes"?

I know this sounds crazy, but the only way I can reproduce that what you're seeing is by entering `localhost` for the "App Domains" but not saving the changes.

**Comment by nolangormley** [comment]
Yup, I just deleted it and made it again. Hit save after putting in `localhost` under App Domains and `http://localhost/` under Site URL. Still got the same issue.

**Comment by specious** [comment]
I'm confused why this isn't working for you.  When I tried to authenticate your app (before you deleted it) to use my account, I got the same result as you.

Now I get:
```
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
```

However, I have a test app that I created recently, so it's listed as using API v2.10, and it authenticates flawlessly.

Try this URL to authenticate mine:

`https://www.facebook.com/dialog/oauth?client_id=460794997638149&redirect_uri=http://localhost:3333/&scope=user_likes,user_friends,user_posts,user_photos,user_videos,user_events,publish_actions`

It should redirect to:

`http://localhost:3333/?code=<authorization-code>`

Which of course won't load, unless `facebook-cli` is listening for the auth code, but shouldn't give you the app domain error.

Thank you for helping me troubleshoot this.

**Comment by specious** [comment]
I just pushed facebook-cli 1.6.1, which [switches to Graph API v2.10](https://github.com/specious/facebook-cli/commit/7d652e852df61b5c4edccbcc808cd9a6a5a38662#diff-5ec4008350faa88cf347e0728eae3d4bR7).

**Comment by nolangormley** [comment]
When I tried that link, it gave me that same 
```
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
```
That you had. I'll try some more troubleshooting later tonight and see if I can get it to work.

**Comment by specious** [comment]
I suppose I'd check whether the "App ID" is the same as the `app_id` in `~/.facebook-clirc`.

I really don't know what else could be causing this.

**Comment by NassimBounouas** [comment]
Hi,

Just to report it.
I tried to configure the app today and got the same issue. I checked alll the configuration and everything is fine according the readme.

Thanks.

**Comment by shfrs** [comment]
I tried using an app that using API v2.8 and it working, but show error same as above when using recently created app that used API v2.10 (I'm using facebook-cli version 1.6.1)

**Comment by shfrs** [comment]
When running `facebook-cli api` I get this error:
`Koala GraphMethodException (code 100, subcode: 33) HTTP status: 400
  Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api (FB trace id: E3Xy0XaOZxh) `

**Comment by gyorfiattila** [comment]
Hi,

Try this. It's works for me.

https://www.nextscripts.com/instructions/facebook-social-networks-auto-poster-setup-installation/october-2017-facebook-changes/

**Comment by specious** [comment]
@gyorfiattila, thank you for pointing us to the source of this error!

From the article:

> Facebook (as usually) made a silent change to it’s API on October 4, 2017.

This coincides precisely with the date @dagormz opened this issue.  Following this clue, I am able to reproduce the same condition by creating a new app, whereas none of the apps I have created before October 4th manifest this symptom.

**Comment by specious** [comment]
Please follow the [updated instructions](https://github.com/specious/facebook-cli/tree/v1.6.2#facebook-setup) in 1.6.2.

Changes (29424ae7e1a62a5515571dc8cc7f3488a223c324) also include better explanation of the login flow and handling of the access token.

Thank all of you guys for helping make facebook-cli more robust!

**Comment by yushinzm** [comment]
shortest way is to add a website as a platform under website platform add localhost as a website domain.

**Comment by Mickamwamba** [comment]
This is from Facebook developer dashboard!

"In March, we're making a security update to your app settings that will invalidate calls from URIs not listed in the Valid OAuth redirect URIs field"

WHAT DO YOU HAVE TO DO?
- Add your site's callback url in the **Valid OAuth redirect URIs field**

**Comment by isccha** [comment]
Also, make sure you are accessing http://localhost:3000 and not http://0.0.0.0:3000.
It looks ridiculous but it is possible.

**Comment by heartgfx** [comment]
I am getting this error same to you.. and ialready do that  your solution but still error  
![image](https://user-images.githubusercontent.com/37492087/37562124-e9670370-2a9a-11e8-910c-2647d58a39a8.png)
![image](https://user-images.githubusercontent.com/37492087/37562129-0c8cab66-2a9b-11e8-839e-cf435b499468.png)
![image](https://user-images.githubusercontent.com/37492087/37562130-1d26fbde-2a9b-11e8-800f-4711ca642f1d.png)

 Someone please help us with this...

**Comment by shaileshkumarkachhi** [comment]
Hover over your current Facebook button on your website, look at the URL of the button, your URL should look something like this:

[https://www.facebook.com/dialog/oauth?type=web_server&client_id=5725505294802769&redirect_uri=https://www.yourdomain.com/_auth/facebook?close&yourparams](url)

Now the important thing is:
Valid Oath redirect URIs:
redirect_uri=https://www.yourdomain.com/_oath/facebook?close&yourparams

See? It literally says this is your actual redirect URI, or the Valid OAuth redirect URI that Facebook now needs from you.

Now cut it down to the “&” our site looks like this:
redirect_uri=https://www.yourdomain.com/_oath/facebook?close

Then it will work :)

**Comment by zhengfen** [comment]
@heartgfx 
I did run into the same problem, then i solved the problem by modified in setting Valid OAuth redirect URIs:
https://dance.zhengfen.ch/callback (instead of https://dance.zhengfen.ch/)
it has to be the redirect url of your app

**Comment by heartgfx** [comment]
you are using appversion 2.10? Have you tried it also on the new version
like v2.12? I already do that but it didn't work I still encountered the
same error

**Comment by zhengfen** [comment]
i am using v2.10, but I did not follow the tutorial related to JavaScript SDK (https://developers.facebook.com/docs/facebook-login/web). I followed this tutorial (https://appdividend.com/2017/07/12/laravel-facebook-login/) I hope it helps

**Comment by kcpal-qode** [comment]
@shaileshpatel91 
For me https://yourdomain.com/login/facebook/callback is working smoothly for logging through facebook. 
But for another services I'm using a separate uri which goes like this:
http://yourdomain.com/clients/authorization/facebook/page?close
and as you said the actual uri is 
http://yourdomain.com/clients/authorization/facebook/page?close&123456
where these numbers are the client id
But it giving me the same error.
Do you have any idea about this?

**Comment by za4emnik** [comment]
If you use Devise ruby gem with facebook omniauth, you just need set `validOAuth redirect URIs` to `http://localhost:3000/users/auth/facebook/callback` on facebook page for developers.

**Comment by henrydabrow** [comment]
Thank You za4emnik, it works! ;)

**Comment by andycorm** [comment]
@za4emnik, are you talking about the "App Domains" section on the "Basic" tab? If so, attempting to use any URL with a port number in it will result in the following error message for me: 
> App domains must match the domain of the Facebook Web Games URL (https), Mobile Site URL, Unity Binary URL, Site URL or Secure Page Tab URL. Please correct these domains: {url I had just entered}

Am I missing something? ☹️

**Comment by za4emnik** [comment]
@andycorm Sorry for the delay in replying.
No, it's "Valid OAuth Redirect URIs" section on the "Facebook login"->"Settings" tab.
The domain on the "App Domains" section on the "Basic" tab must match with "Site URL".
If you are developing locally, you need set these sections like this.
![app_domains_facebook](https://user-images.githubusercontent.com/15184622/39779944-68c28374-5313-11e8-9f5a-77a4d9ff337d.png)

**Comment by Kallaste** [comment]
I think the problem some people are having with this (not all, but some) is that there are **two** sections for adding domains to the Facebook app. You need the one that says "Valid OAuth Redirect URIs" in the Facebook Login section (under products), **not** just the one that says "App Domains" under Settings > Basic.

<img width="1266" alt="screen shot 2018-05-17 at 6 29 59 pm" src="https://user-images.githubusercontent.com/5215504/40213141-64af2046-5a00-11e8-9653-b201ec41d7c0.png">

**Comment by freakynit** [comment]
Why the hell it doesn't work. Have tried all permutations and combinations. Have also tried removing App Domains all together, still won't work.
Here are the screenshots (I'm using ngrok for testing)
<img width="471" alt="screen shot 2018-05-26 at 10 51 47 am" src="https://user-images.githubusercontent.com/745352/40572798-8561ff00-60d3-11e8-8e7a-bd68c30a6bea.png">
<img width="446" alt="screen shot 2018-05-26 at 10 53 00 am" src="https://user-images.githubusercontent.com/745352/40572799-85936932-60d3-11e8-9d79-a0b066892aba.png">
<img width="341" alt="screen shot 2018-05-26 at 10 53 23 am" src="https://user-images.githubusercontent.com/745352/40572800-85bdca1a-60d3-11e8-8191-bead9bfb6899.png">
<img width="561" alt="screen shot 2018-05-26 at 10 54 01 am" src="https://user-images.githubusercontent.com/745352/40572801-85e8253a-60d3-11e8-9434-e416a8dc1a42.png">

**Comment by Ohmdesbois** [comment]
The solution was for me and for a Drupal8 site [on this page](https://www.drupal.org/docs/8/modules/social-api/social-api-2x/social-auth-2x/social-auth-facebook-2x-installation)
Below are the indications that helped me.
For Authorized redirect URIs, enter the full url to your drupal project + /user/login/facebook/callback. For example, consider that your domain is http://www.example.com but your drupal project is in http://www.example.com/drupal. In this case you should enter http://www.example.com/drupal/user/login/facebook/callback

**Comment by GeniaT** [comment]
Went through all the issue, tried all combinations as well but still have this error.
The platform is added as "website",  the App domain is set to "localhost" and the website set to "http://localhost" as advised before. + I set desperately all possible OAuth URIs. 
@Mickamwamba I am not sure about what url to put in there for my app. I set all possible combinations in there: localhost, the deployed version of the app on heroku + even myapp.firebaseapp.com url. But still same issue as others here... 

EDIT: Instead of deleting my comment, here how I got unstucked: My OAuth uri for my firebase app was simply 'https://myapp.firebaseapp.com/__/auth/handler', I had more characters in the URI after /auth/handler'. solved for me.

**Comment by paramsmit** [comment]
what about the react-native app
i am running my backend on the same machine (localhost)
what is the solution

**Comment by kundan1988** [comment]
Just add “Valid OAuth Redirect URLs
http://localhost/callback under Products/ Facebook Login

And set your site URL to
http://localhost/callback

**Comment by pmutua** [comment]
Adding `http://localhost/callback` will not work. You will end up getting a prompt :
`HTTPS is required for all Redirect URIs` 

Also when you try to add `localhost`  in  App Domains it will not work either you will be prompted:
```
App domains must match the domain of the Facebook Web Games URL (https),
Mobile Site URL, Unity Binary URL, Site URL or Secure Page Tab URL. 
Please correct these domains: localhost.
```

**Comment by pleerock** [comment]
@pmutua did you fix your issue?

**Comment by specious** [comment]
Just for the record, this thread has not been about facebook-cli since quite some time ago.
