### ISSUE TITLE
Remote Server

### ISSUE THREAD

**Issue by derBingle** [specious/facebook-cli#2]
I am SSHed into a Google Compute Engine instance a lot during the day and I wanted to run facebook-cli on it, but it never receives the authorization code since the browser opens in a browser on my laptop vs the server. 

Is there an easy way to manually input the authorization code?

**Comment by specious** [comment]
Once you create the `~/.facebook-clirc` file by authenticating on a local machine, you can copy it to the remote machine and `facebook-cli` should work from there.
