### ISSUE TITLE
thinking of starting a similar project

### ISSUE THREAD

**Issue by negatratoron** [specious/facebook-cli#21]
Would use a headless browser to interact with Facebook.  Advantages: not limited by graph api.  Disadvantages: breaks whenever Facebook changes their page layout.

**Comment by specious** [comment]
I’ve had the same thoughts.  I’d love to see anything you come up with.

**Comment by specious** [comment]
In fact, the headless browser technique could be useful for pulling the list of friends with links to their profiles and profile pictures: https://github.com/specious/facebook-friends/issues/1
