### ISSUE TITLE
Error installing gem

### ISSUE THREAD

**Issue by nivek1385** [specious/facebook-cli#27]
When I run a sudo gem install facebook-cli, I get the below error. I noticed previously that there was an error building the json native extension, so I installed the one available in the apt repo (1.8.1), but that was no help as I'm now running into this error. I also did a gem update --system previous to this.

`Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.14.0.gem (100%)
Successfully installed faraday-0.14.0
Fetching: public_suffix-3.0.2.gem (100%)
Successfully installed public_suffix-3.0.2
Fetching: addressable-2.5.2.gem (100%)
Successfully installed addressable-2.5.2
Building native extensions. This could take a while...
ERROR:  Error installing facebook-cli:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.1.0/gems/json-2.1.0/ext/json/ext/generator
/usr/bin/ruby2.1 -r ./siteconf20180316-9695-mbrld7.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.1.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /var/lib/gems/2.1.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
<built-in>: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:224: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.1.0/gems/json-2.1.0 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/json-2.1.0/gem_make.out
`

**Comment by jremydeaton** [comment]
Getting the same as well

**Comment by nivek1385** [comment]
Restarting the computer and trying again resolved the issue.
