### ISSUE TITLE
Post to a Facebook group

### ISSUE THREAD

**Issue by thanos-k** [specious/facebook-cli#4]
Is it possible to add functionality so that I can post to a Group I am a member ?
I know you can do it using an oAuth token using something like this  
put_connections(1111111111111111, "feed", :message => "Test page wall post")

but that is sort lived and not very practical (assuming we already know the group id)

is it possible to integrate it in the cli or it is not even possible ?

**Comment by thanos-k** [comment]
It seems it is possible so I will submit a pull request in a few days when I cleaned up the code a bit :)

**Comment by specious** [comment]
Thank you for making a contribution.  Please take your time, as I really appreciate code quality.

**Comment by thanos-k** [comment]
Considering I am not a developer and never before have I worked with the FB API I hope the code is at least clean enough since I only wanted this functionality for a small side-project.

Btw since I barely understand FB oAuth token system can you please confirm that once you get the long lived token you don't actually need to refresh it every 60 days as long as you use the app during that time period ?

**Comment by specious** [comment]
I'm closing this thread, since we can continue the discussion in #5.
