### ISSUE TITLE
Readme mentions configuring website localhost

### ISSUE THREAD

**Issue by kabads** [specious/facebook-cli#7]
It seems that Facebook have pulled the option to identify the app as a website. I'm finding it problematic to identify this at Facebook's end. Is it necessary?

**Comment by specious** [comment]
I see that they've changed their user interface, and the "choosing your platform" workflow is different now.  You can still choose the "website" option, and then click "Skip Quick Start" on the next page.

![choose-app-platform](https://cloud.githubusercontent.com/assets/451178/25909141/30f1e5f0-357a-11e7-93d4-c9378dbbc1fc.png)

It is necessary to label your new Facebook app as a "website" with a URL of `http://localhost` in order for the server started by `facebook-cli` to [receive the Facebook login authorization code](https://github.com/specious/facebook-cli/blob/02f5a4af5293864292a578e15f4f7bef56b97f04/lib/fbcli/auth.rb#L16) after initiating the login procedure in your web browser.
