### ISSUE TITLE
SSL issue at rubygems?

### ISSUE THREAD

**Issue by fredzannarbor** [specious/facebook-cli#8]
Not sure if this is at my end or rubygems.org, but it's stopping me from installing.

gem install facebook-cli
```
ERROR:  Could not find a valid gem 'facebook-cli' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)

```

**Comment by specious** [comment]
I think this is more of a [rubygems](https://github.com/rubygems/rubygems) issue.  A search for `ssl` on the rubygems project yields a number of similar [results](https://github.com/rubygems/rubygems/issues?q=is%3Aissue+ssl).

For example, https://github.com/rubygems/rubygems/issues/1912 opened 8 days ago.

Thank you for bringing this up.

**Comment by specious** [comment]
I'm closing this issue.  Please reopen if evidence points to a problem with facebook-cli.
